### PR TITLE
exposing selectYears and selectMonths

### PR DESCRIPTION
**Pull request by raoulus**
makes it configurable from outside

```javascript
datePicker: {
  type: 'datepicker',
  selectYears: true,
  selectMonths: true
}
```

### CODE REVIEW

**Comment by Dervisevic** [comment]
There's a broken test, is that something you could take a look at?

**Comment by raoulus** [comment]
sure, let me check

**Comment by raoulus** [comment]
@Dervisevic tests are passing. I had to upgrade PhantomJS.

**Comment by raoulus** [comment]
I just noticed that it is already possible to pass the options also in the current version by the following form definition:

```
datePicker: {
  type: 'datepicker',
  pickadate: {
    selectYears: true,
    selectMonths: true
  }
}
```

This PR provides then just a shortcut.

**Comment by raoulus** [comment]
@Dervisevic is there a change to get this merged?

**Comment by raoulus** [comment]
@Dervisevic any news?

**Comment by Dervisevic** [comment]
I'm currently not available, @kornosaurus, could you take a look?

**Comment by kornosaurus** [comment]
This looks good, merging this without commit b9c4d07 as mentioned in #42

**Pull request merged**
